trigger:
  - none

pr:
  - none

variables:
  - name: deploymentRegion
    value: canadacentral
  - name: serviceConnection
    value: AzureLabCACN-Sponosored
  - name: vmWinImage
    value: windows-latest
  - name: vmImage
    value: ubuntu-latest
  - name: deployOperation
    value: create
  - name: var-bashPostInjectScript
    value: ':'
  - name: var-bashPreInjectScript
    value: 'set -E; function catch { echo "##vso[task.logissue type=error]Caller: $(caller), LineNo: $LINENO, Command: $BASH_COMMAND" ; exit 1 ; } ; echo ; echo "Current working directory: $(pwd)" ; echo ; trap catch ERR'
  - name: avdShrdlSubsId
    value: a165ed8a-0e83-46f1-9994-b216229c2da7
  - name: avdWrklSubsId
    value: a165ed8a-0e83-46f1-9994-b216229c2da7
  - name: avdWrklSecretAccess
    value: 8e23a491-5178-4c69-9fce-1377e52a29c6
  - name: createAvdVnet
    value: false
  - name: useSharedImage
    value: false
  - name: avdOsImage
    #value: win11_21h2_office
    #value: win10_21h2
    value: win10_21h2_office
    #value: win11_21h2
  - name: avdIdentityDomainName
    value: azureminilab.com
  - name: avdDomainJoinUserName
    value: 'azadmin@azureminilab.com'
  - name: avdDomainJoinUserPassword
    value: '!V0ipc@123'
  - name: avdVmLocalUserName
    value: azadmin
  - name: avdVmLocalUserPassword
    value: '!R37fallacy1505'


stages:
  - stage: Deploy_AVD_Accelerator
    displayName: Deploy AVD Accelerator
    jobs:
      # Deploy template deploy-baseline.bicep for AVD Accelerator
      - template: deploy-template-sub.yml
        parameters:
          jobName: Deploy_AVD_Accelerator
          location: $(deploymentRegion)
          workingDir: $(System.DefaultWorkingDirectory)/workload
          templateFile: deploy-baseline.bicep
          parameterArray:
            - deploymentPrefix 'app1'
            - avdDeploySessionHostsCount 1
            - avdWorkloadSubsId $(avdWrklSubsId)
            - avdEnterpriseAppObjectId '82205950-fef1-4f88-8801-86e60c2e9318'
            - avdManagementPlaneLocation $(deploymentRegion)
            - avdSessionHostLocation $(deploymentRegion)
            - fsLogixstorageSku 'Standard_LRS'
        #    - avdWrklSecretAccess $(avdWrklSecretAccess)
            - existingVnetSubnetResourceId '/subscriptions/a165ed8a-0e83-46f1-9994-b216229c2da7/resourceGroups/azurelab-avd-networking/providers/Microsoft.Network/virtualNetworks/vnet-avd-canadacentral/subnets/subnet1'
            - existingHubVnetResourceId '/subscriptions/4f6c98e1-04a4-49f0-abce-6240b1726c3f/resourceGroups/pubsec-hub-networking-rg/providers/Microsoft.Network/virtualNetworks/hub-vnet'
            - useSharedImage $(useSharedImage)
            - avdOsImage $(avdOsImage)
            - createAvdVnet $(createAvdVnet)
            - avdIdentityDomainName $(avdIdentityDomainName)
            - avdDomainJoinUserName $(avdDomainJoinUserName)
            - avdDomainJoinUserPassword $(avdDomainJoinUserPassword)
            - avdVmLocalUserName $(avdVmLocalUserName)
            - avdVmLocalUserPassword $(avdVmLocalUserPassword)
            - avdDeployRAppGroup true
            - avdDeploySessionHosts true
            - avdStartVMOnConnect true
            - createStartVmOnConnectCustomRole true
            - vNetworkGatewayOnHub false
            - createOUforStorage true
            - storageOUName 'FsLogix User Profiles'
