name: Bug Report
description: File a bug report
title: "[PLACEHOLDER] - Place a descriptive title here"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Provide a clear and concise description of the bug, including deployment details.
    validations:
      required: true
  - type: textarea
    id: correlation-id
    attributes:
      label: Please provide the correlation id associated with your error or bug. 
      description: You can use the example [here](https://learn.microsoft.com/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal) on how to find it
      value: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    validations:
      required: false
  - type: textarea
    id: what-is-expected
    attributes:
      label: What was the expected outcome?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
