name: General Feedback
description: Tell us what you think!
title: "[PLACEHOLDER] - Place a descriptive title here"
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        We always appreciate the community involvement! Let us know your feedback.
  - type: textarea
    id: describe-feedback
    attributes:
      label: Let us know the feedback or general question
      value: "Feedback - Question"
    validations:
      required: true