module "management_vm"{
  source = "../../modules/mgmtvm"


    workloadSubsId = var.spoke_subscription_id
    tenant_id = data.azurerm_client_config.current.tenant_id
    
    publisher = "MicrosoftWindowsServer"
    offer = "WindowsServer"
    sku = "2022-datacenter-smalldisk-g2"
    domain_name = var.domain_name
    domain_user = var.domain_user
    domain_password = var.domain_password
    vm_size = "Standard_B2ms"
   
    local_admin_username = var.local_admin_username
    localpassword = var.domain_password                     ##### ToDo: This should be changed by one password generated by keyvault!!!!!
    
    avdLocation = var.avdLocation
    rg_so = var.rg_so
    rg_stor = var.rg_stor
    prefix = var.prefix

    vnet_ID = module.network.vnet_id
    snet_ID = module.network.subnet_subnet_id
    rg_network = module.network.rg_name
    spoke_subscription_id = var.spoke_subscription_id
    fsshare = azurerm_storage_share.FSShare.name            ##### Este deberia existir???
    storage_account_name = azurerm_storage_account.storage.name
    storage_account_rg = azurerm_resource_group.rg_storage.name
    IdentityServiceProvider = "ADDS"
    location = var.avdLocation
    domainJoinUserPassword = var.domain_password

    #Aun no estoy seguro de estos valores!!!
    baseScriptUri = "https://raw.githubusercontent.com/sihbher/avdaccelerator/main/workload/scripts/Manual-DSC-Storage-Scripts.ps1"
    dsc_storage_path="https://github.com/sihbher/avdaccelerator/raw/main/workload/scripts/DSCStorageScripts-01.zip"
    vfile = "Manual-DSC-Storage-Scripts.ps1"
    security_principal_name= var.aad_group_name
    ou_name = "AvdComputers"
    custom_ou_path = var.ou_path


    #Validate!
    scriptArguments=""
    create_ou_for_storage_string= "true" #validate this value



  depends_on = [
    
    azurerm_resource_group.rg,
    azurerm_resource_group.shrg, 
    azurerm_virtual_desktop_host_pool.hostpool,
    azurerm_virtual_desktop_workspace.workspace,
    azurerm_virtual_desktop_application_group.dag,
    azurerm_storage_account.storage,
    module.network
  ]

}
