module "management_vm"{
  source = "../../modules/mgmtvm"

  #dsc_storage_path = '', I will use default value
#   rg_so = azurerm_resource_group.rg.name
  workloadSubsId = var.spoke_subscription_id
deployment_environment = var.prefix
#azure_cloud_environment = '', will use default value
    create_ou_for_storage_string= "true" #validate this value
    publisher = "MicrosoftWindowsServer"
    offer = "WindowsServer"
    sku = "2022-datacenter-smalldisk-g2"
    domain_name = var.domain_name
    domain_user = var.domain_user
    domain_password = var.domain_password
    vm_size = "Standard_B2ms"
    ou_path = var.ou_path
    custom_ou_path = "" #validate this value
    local_admin_username = var.local_admin_username
    localpassword = var.domain_password                     ##### ToDo: This should be changed by one password generated by keyvault!!!!!
    
    avdLocation = var.avdLocation
    rg_so = var.rg_so
    rg_stor = var.rg_stor
    prefix = var.prefix

    vnet_ID = module.network.vnet_id
    snet_ID = module.network.subnet_subnet_id
    rg_network = module.network.rg_name
    spoke_subscription_id = var.spoke_subscription_id
    fsshare = azurerm_storage_share.FSShare.name            ##### Este deberia existir???
    storage_account_name = azurerm_storage_account.storage.name
    storage_account_rg = azurerm_resource_group.rg_storage.name
    IdentityServiceProvider = "ADDS"
    location = var.avdLocation
    domainJoinUserPassword = var.domain_password

    #Aun no estoy seguro de estos valores!!!
    baseScriptUri = "https://github.com/Azure/avdaccelerator/blob/main/workload/scripts"
    vfile = "Manual-DSC-Storage-Scripts.ps1"
    scriptArguments=""




  depends_on = [
    
    azurerm_resource_group.rg,
    azurerm_virtual_desktop_host_pool.hostpool,
    azurerm_virtual_desktop_workspace.workspace,
    azurerm_virtual_desktop_application_group.dag,
    azurerm_storage_account.storage
  ]

}
