# This workflow uses actions to scan for accessibility
name: Accessibility Scan

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install axe-core and http-server
      run: npm install -g axe-core http-server

    - name: Start local server
      run: |
        nohup http-server ./ &

    - name: Create axe-reports directory
      run: mkdir -p ./axe-reports

    - name: Run axe-core accessibility scan
      run: |
        npx axe-core http://localhost:8080 --output html --output-path ./axe-reports/accessibility-report.html

    - name: Verify report creation
      run: |
        ls -la ./axe-reports/
        cat ./axe-reports/accessibility-report.html || echo "Report not created"

    - name: Upload axe-core report
      uses: actions/upload-artifact@v3
      with:
        name: axe-report
        path: ./axe-reports/accessibility-report.html
