# This workflow uses actions to scan for accessibility
name: Accessibility Scan

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install axe-cli and http-server
      run: npm install -g axe-cli http-server

    - name: Start local server
      run: |
        nohup http-server ./ &

    - name: Wait for the server to start
      run: sleep 5  # Wait for 5 seconds to ensure server is ready

    - name: Create axe-reports directory
      run: mkdir -p ./axe-reports

    - name: Run axe-cli accessibility scan with save flag
      run: |
        npx axe-cli http://localhost:8080 --save --dir ./axe-reports
        echo "Checking if the report was saved..."

    - name: List contents of axe-reports directory
      run: |
        echo "Listing contents of the axe-reports directory:"
        ls -la ./axe-reports/
        echo "Attempting to read the report content:"
        cat ./axe-reports/accessibility-report.html || echo "Report not created"

    - name: Upload axe-core report
      uses: actions/upload-artifact@v3
      with:
        name: axe-report
        path: ./axe-reports/accessibility-report.html

