# This workflow uses actions to scan for accessibility
name: Accessibility Scan

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install axe-cli globally
      run: npm install -g axe-cli

    - name: Run axe-cli accessibility scan
      run: npx axe ./ --output html --output-path ./axe-reports/accessibility-report.html

    - name: Upload axe-core report
      uses: actions/upload-artifact@v3
      with:
        name: axe-report
        path: ./axe-reports/accessibility-report.html
